name: Linux Build

on: workflow_call

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25-ea+36'
          distribution: 'graalvm-community'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute dist build
        run: ./gradlew clean dist --stacktrace
        env:
          RELEASE: ${{ contains(github.event.head_commit.message, '[release]') == true }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          retention-days: 1
          compression-level: 1
          path: dist/build/dist/artifacts/*
